### ISSUE TITLE
AssertionError: Path expected

### ISSUE THREAD

**Issue by 1N50MN14** [lasso-js/lasso-imagemin#2]
I'm configuring the plugin in accordance to the sample code, however it's throwing an assertion error for some reason.

My plugin configuration can be found here: https://gist.github.com/1N50MN14/db7e1aface979ae7bcba

**Comment by austinkelleher** [comment]
Sorry for the very late response. PR #3 fixes this issue. Published `lasso-imagemin@1.0.8` with the fix.
